//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullaniciGiris
    {
        public int kullaniciID { get; set; }
        public string mailAdres { get; set; }
        public string sifre { get; set; }
        public string adSoyad { get; set; }
        public Nullable<int> yas { get; set; }
        public string departman { get; set; }
        public string adres { get; set; }
        public string telefonNo { get; set; }
    }
}
